import { buildPayslipDoc, buildRetentionTransactions, type PayslipInput } from "@/lib/payslip";
import { writeFileSync } from "fs";
const rev = Array.from({length: 34}, (_,i) => ({ date: `2026-07-${String((i%28)+1).padStart(2,'0')}`, amount: 500+i*37, method: ["wire","card","crypto"][i%3], employee_id: "e1", employee_id_2: i%5===0 ? "e2" : null, split_pct: i%5===0 ? 60 : 100 }));
const wds = [{date:"2026-07-05",amount:2000,employee_penalty:200},{date:"2026-07-19",amount:1500,employee_penalty:150}];
const tx = buildRetentionTransactions({ employeeId:"e1", revenue: rev, withdrawals: wds, commissionPct: 10, defaultPenaltyPct: 10 });
const p: PayslipInput = { companyName:"Ledgerly Ltd", employeeName:"Valerie Ramirez", teamLabel:"Retention", role:"Retention agent", month:"2026-07", baseSalary:3000, workingDays:23, absentDays:2, perDayRate:130.4, absenceDeduction:260.8, ftdCount:0, ftdRate:0, ftdCommission:0, revenueBase:tx.totals.deposits, commissionPct:10, revenueCommission:tx.totals.netCommission, stdCount:4, stdRate:50, stdBonus:200, withdrawalPenalty:350, transactions:tx };
writeFileSync("/tmp/qa/r.pdf", Buffer.from(buildPayslipDoc(p).output("arraybuffer")));
const deficit = { ...p, revenueCommission: 20, stdBonus: 0, transactions: { ...tx, totals: { ...tx.totals, commissionEarned: 30, feeDeducted: 10, netCommission: 20 }, revenue: tx.revenue.slice(0,2) } };
writeFileSync("/tmp/qa/deficit.pdf", Buffer.from(buildPayslipDoc(deficit as any).output("arraybuffer")));
const c = { ...p, teamLabel:"Conversion", ftdCount:12, ftdRate:100, ftdCommission:1200, revenueCommission:0, stdCount:0, stdBonus:0, withdrawalPenalty:0, transactions: undefined };
writeFileSync("/tmp/qa/c.pdf", Buffer.from(buildPayslipDoc(c as any).output("arraybuffer")));
